Silent curls and add logs to bash scripts

diff --git a/manifests/on-prem/frr.yaml b/manifests/on-prem/frr.yaml
--- a/manifests/on-prem/frr.yaml
+++ b/manifests/on-prem/frr.yaml
@@ -111,10 +111,10 @@ spec:
           # takes one argument: the VIP to check.
           local vip=$1
           if ip address show dev lo | grep -q $vip; then
-              echo "VIP $vip is assigned to this node"
+              echo `date "+%FT%T"` "VIP $vip is assigned to this node"
               return 0
           else
-              echo "VIP $vip is not assigned to this node"
+              echo `date "+%FT%T"` "VIP $vip is not assigned to this node"
               return 1
           fi
       }
@@ -140,11 +140,11 @@ spec:
           # takes one argument: the VIP to route.
           local vip=$1
           if ! ip rule show table 168 | grep -q $vip; then
-              echo "Create ip rule for $NETWORK_CIDR in table 168"
+              echo `date "+%FT%T"` "Create ip rule for $NETWORK_CIDR in table 168"
               ip rule add from $vip to $NETWORK_CIDR lookup 168
           fi
           if ! ip route show table 168 | grep -q $GATEWAY; then
-              echo "Create default route for table 168 via $GATEWAY"
+              echo `date "+%FT%T"` "Create default route for table 168 via $GATEWAY"
               ip route add default via $GATEWAY table 168
           fi
       }
@@ -155,7 +155,7 @@ spec:
           # takes one argument: the VIP to create.
           local vip=$1
           if ! ip address show dev lo | grep -q $vip; then
-            echo "Creating VIP $vip"
+            echo `date "+%FT%T"` "Creating VIP $vip"
             ip address add $vip dev lo
           fi
       }
@@ -165,7 +165,7 @@ spec:
           # takes one argument: the VIP to delete.
           local vip=$1
           if ip address show dev lo | grep -q $vip; then
-            echo "Deleting VIP $vip"
+            echo `date "+%FT%T"` "Deleting VIP $vip"
             ip address del $vip dev lo
           fi
       }
@@ -173,7 +173,7 @@ spec:
       start_all_vips()
       {
         VIP_NETMASK=32
-        echo "Starting all VIPs"
+        echo `date "+%FT%T"` "Starting all VIPs"
         for vip in $VIPS; do
           create_vip $vip/$VIP_NETMASK
           create_vip_routing $vip
@@ -183,7 +183,7 @@ spec:
       stop_all_vips()
       {
         VIP_NETMASK=32
-        echo "Stopping all VIPs"
+        echo `date "+%FT%T"` "Stopping all VIPs"
         for vip in $VIPS; do
           delete_vip $vip/$VIP_NETMASK
         done
@@ -191,7 +191,7 @@ spec:
       
       stop_frr()
       {
-        echo "Frr process stopped" >> /var/run/frr/stopped
+        echo `date "+%FT%T"` "Frr process stopped" >> /var/run/frr/stopped
         stop_all_vips
         [ -r /var/run/frr/watchfrr.pid ] && /usr/libexec/frr/frr stop
       }
@@ -199,7 +199,7 @@ spec:
       msg_handler()
       {
         while read -r line; do
-          echo "The client sent: $line" >&2
+          echo `date "+%FT%T"` "The client sent: $line" >&2
           # currently only 'stop' messages are supported
           if  [ "$line" = stop ]; then
               stop_frr
@@ -222,14 +222,14 @@ spec:
       export -f stop_frr
       
       while [ -s "/var/run/frr/stopped" ]; do
-         echo "Container stopped"
+         echo `date "+%FT%T"` "Container stopped"
          sleep 60
       done
       if timeout 30s bash -c "while true; do [ -f /etc/frr/frr.conf ] && break; done"; then
           start_all_vips
           /usr/libexec/frr/frr start
       else
-          echo "ERROR: /etc/frr/frr.conf was not found"
+          echo `date "+%FT%T"` "ERROR: /etc/frr/frr.conf was not found"
           exit 1
       fi
       rm -f "$frr_sock"
