templates/*: backup restore etcd pod yaml
The restore etcd pod yaml needs to be backed up so it is consumes the
on revisions where were present at the time of the backup.

diff --git a/templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml b/templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
--- a/templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
+++ b/templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
@@ -74,8 +74,15 @@ contents:
           exit 1
       fi
 
+      ETCD_RESTORE_POD=$(ls /etc/kubernetes/static-pod-resources/etcd-certs/configmaps/restore-etcd-pod/pod.yaml) || true
+      if [ -z "$ETCD_RESTORE_POD" ]; then
+          echo "error finding restore pod yaml"
+          exit 1
+      fi
+
+
       # tar up the static kube resources, with the path relative to CONFIG_FILE_DIR
-      tar -cpzf $BACKUP_TAR_FILE -C ${CONFIG_FILE_DIR} ${LATEST_STATIC_POD_DIR#$CONFIG_FILE_DIR/} ${LATEST_ETCD_STATIC_POD_DIR#$CONFIG_FILE_DIR/}
+      tar -cpzf $BACKUP_TAR_FILE -C ${CONFIG_FILE_DIR} ${LATEST_STATIC_POD_DIR#$CONFIG_FILE_DIR/} ${LATEST_ETCD_STATIC_POD_DIR#$CONFIG_FILE_DIR/} ${ETCD_RESTORE_POD#$CONFIG_FILE_DIR/}
     }
 
     append_snapshot_to_tar_and_gzip() {
