DR: add validate_environment to openshift-recovery-tools
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

diff --git a/templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml b/templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
--- a/templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
+++ b/templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
@@ -4,47 +4,58 @@ path: "/usr/local/bin/etcd-snapshot-restore.sh"
 contents:
   inline: |
     #!/usr/bin/env bash
-    
+
     set -o errexit
     set -o pipefail
-    
+
     # example
-    
     # etcd-snapshot-restore.sh $path-to-snapshot $etcd-connection-string
+
     if [[ $EUID -ne 0 ]]; then
       echo "This script must be run as root"
       exit 1
     fi
-    
-    ASSET_DIR=./assets
-    SNAPSHOT_FILE="${ASSET_DIR}/backup/etcd/member/snap/db"
-    
-    if [ "$1" != "" ]; then
-      SNAPSHOT_FILE="$1"
-    fi
-    
 
+    usage () {
+        echo 'Path to snapshot is required: ./etcd-member-recover.sh $path-to-snapshot'
+        exit
+    }
+
+    if [ "$1" == "" ]; then
+        usage
+    fi
+
+    SNAPSHOT_FILE="$1"
     ETCD_CONNSTRING=""
     if [ "$2" != "" ]; then
       ETCD_CONNSTRING="$2"
     fi
 
+    ASSET_DIR=./assets
     CONFIG_FILE_DIR=/etc/kubernetes
     MANIFEST_DIR="${CONFIG_FILE_DIR}/manifests"
     MANIFEST_STOPPED_DIR="${ASSET_DIR}/manifests-stopped"
+    RUN_ENV=/run/etcd/environment
+
     ETCD_VERSION=v3.3.10
     ETCDCTL="${ASSET_DIR}/bin/etcdctl"
     ETCD_DATA_DIR=/var/lib/etcd
     ETCD_MANIFEST="${MANIFEST_DIR}/etcd-member.yaml"
     ETCD_STATIC_RESOURCES="${CONFIG_FILE_DIR}/static-pod-resources/etcd-member"
     STOPPED_STATIC_PODS="${ASSET_DIR}/tmp/stopped-static-pods"
-    
+
     source "/usr/local/bin/openshift-recovery-tools"
-    
+
     function run {
       init
       dl_etcdctl
       backup_manifest
+      DISCOVERY_DOMAIN=$(grep -oP '(?<=discovery-srv=).*[^"]' $ASSET_DIR/backup/etcd-member.yaml )
+      if [ -z "$DISCOVERY_DOMAIN" ]; then
+        echo "Discovery domain can not be extracted from $ASSET_DIR/backup/etcd-member.yaml"
+        exit 1
+      fi
+      validate_environment
       stop_static_pods
       stop_etcd
       stop_kubelet
@@ -55,5 +66,5 @@ contents:
       start_static_pods
       start_kubelet
     }
-    
+
     run
