Add conntrack to gcp route script

diff --git a/templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml b/templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
--- a/templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
+++ b/templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
@@ -93,6 +93,11 @@ contents:
                 ensure_rule nat "${CHAIN_NAME}-local" --dst "${vip}" -j REDIRECT
             fi
         done
+        sleep 5
+        for vip in "${!vips[@]}"; do
+            echo "Removing stale conntrack connections for ${vip}"
+            conntrack -D -r "${vip}" || echo "unable to run conntrack"
+        done
     }
 
     clear_rules() {
