Add service dependencies for openvswitch-ipsec.service
The openvswitch-ipsec service must be started only after ipsec.service
and it has to be up before crio and kubelet service, so add appropriate
systemd service dependencies for openvswitch-ipsec.service.

It also removes a workaround that was needed in ipsec-connect-wait
script to explicitly trigger pluto to establish IPSec IKE SAs with
peer nodes when openvswitch-ipsec.service is already running on
the node.

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

diff --git a/templates/common/_base/files/wait-for-ipsec-connect.yaml b/templates/common/_base/files/wait-for-ipsec-connect.yaml
--- a/templates/common/_base/files/wait-for-ipsec-connect.yaml
+++ b/templates/common/_base/files/wait-for-ipsec-connect.yaml
@@ -4,25 +4,31 @@ contents:
   inline: |
     #!/bin/bash
     set -x
+    set -o pipefail
 
     if [ ! -e "/etc/ipsec.d/openshift.conf" ]; then
       exit 0
     fi
 
-    # Modify existing IPsec out connection entries with "auto=start"
-    # option and restart ipsec systemd service. This helps to
-    # establish IKE SAs for the existing IPsec connections with
-    # peer nodes. This option will be deleted from connections
-    # once ovs-monitor-ipsec process spinned up on the node by
-    # ovn-ipsec-host pod, but still it won't reestablish IKE SAs
-    # again with peer nodes, so it shouldn't be a problem.
-    # We are updating only out connections with "auto=start" to
-    # avoid cross stream issue with Libreswan 5.2.
-    # The in connections use default auto=route parameter.
-    if ! grep -q "auto=start" /etc/ipsec.d/openshift.conf; then
-      sed -i '/^.*conn ovn.*-out-1$/a\    auto=start' /etc/ipsec.d/openshift.conf
+    ovsipsecsvc="openvswitch-ipsec.service"
+    if ! systemctl is-active --quiet $ovsipsecsvc; then
+      echo "$ovsipsecsvc is not running, so make pluto to establish IKE SAs"
+
+      # Modify existing IPsec out connection entries with "auto=start"
+      # option and restart ipsec systemd service. This helps to
+      # establish IKE SAs for the existing IPsec connections with
+      # peer nodes. This option will be deleted from connections
+      # once ovs-monitor-ipsec process spinned up on the node by
+      # ovn-ipsec-host pod, but still it won't reestablish IKE SAs
+      # again with peer nodes, so it shouldn't be a problem.
+      # We are updating only out connections with "auto=start" to
+      # avoid cross stream issue with Libreswan 5.2.
+      # The in connections use default auto=route parameter.
+      if ! grep -q "auto=start" /etc/ipsec.d/openshift.conf; then
+        sed -i '/^.*conn ovn.*-out-1$/a\    auto=start' /etc/ipsec.d/openshift.conf
+      fi
+      chroot /proc/1/root ipsec restart
     fi
-    chroot /proc/1/root ipsec restart
 
     # Wait for upto 60s to get IPsec SAs to establish with peer nodes.
     timeout=60
@@ -30,7 +36,13 @@ contents:
     desiredconn=""
     establishedsa=""
     while [[ $elapsed -lt $timeout ]]; do
-      desiredconn=$(grep -E '^\s*conn\s+' /etc/ipsec.d/openshift.conf | grep -v '%default' | awk '{print $2}' | tr ' ' '\n' | sort | tr '\n' ' ')
+      if ! desiredconn=$(ovs-vsctl --bare --columns=name find interface type=geneve options:remote_name!='""' \
+       | sort \
+       | awk 'NF {print $0"-in-1", $0"-out-1"}' \
+       | tr '\n' ' '); then
+        echo "failed to query OVS Geneve interfaces for desired IPsec connections"
+        exit 0
+      fi
       establishedsa=$(ipsec showstates | grep ESTABLISHED_CHILD_SA | grep -o '"[^"]*"' | sed 's/"//g' | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
       if [ "$desiredconn" == "$establishedsa" ]; then
         echo "IPsec SAs are established for desired connections after ${elapsed}s"
