Start openvswith-ipsec systemd service
When openvswith-ipsec systemd service is already configured for OVN, then let
wait-for-ipsec-connect.service start it immediately and then start waiting
for IKE SA to be established.

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

diff --git a/templates/common/_base/files/wait-for-ipsec-connect.yaml b/templates/common/_base/files/wait-for-ipsec-connect.yaml
--- a/templates/common/_base/files/wait-for-ipsec-connect.yaml
+++ b/templates/common/_base/files/wait-for-ipsec-connect.yaml
@@ -10,9 +10,20 @@ contents:
       exit 0
     fi
 
+    # If "openshift.conf" is referenced in /etc/sysconfig/openvswitch,
+    # the ovn-ipsec-host pod has already configured the openvswitch-ipsec
+    # systemd service for establishing OVN IPsec connections.
+    # However, the machine-config-daemon pod may reset this service to
+    # a disabled state, causing it not to start after a node reboot.
+    # To handle this scenario, enable and start the service here as well.
     ovsipsecsvc="openvswitch-ipsec.service"
-    if ! systemctl is-active --quiet $ovsipsecsvc; then
-      echo "$ovsipsecsvc is not running, so make pluto to establish IKE SAs"
+    if grep -q "openshift.conf" /etc/sysconfig/openvswitch; then
+      if ! systemctl enable --now $ovsipsecsvc; then
+        echo "Failed to enable and start $ovsipsecsvc"
+        exit 1
+      fi
+    else
+      echo "$ovsipsecsvc is not configured, so make pluto to establish IKE SAs"
 
       # Modify existing IPsec out connection entries with "auto=start"
       # option and restart ipsec systemd service. This helps to
@@ -31,6 +42,12 @@ contents:
     fi
 
     # Wait for upto 60s to get IPsec SAs to establish with peer nodes.
+    # We derived total wait time 60s based on the testing from 6 and 32 nodes
+    # cluster. In 6 node cluster, it took mostly about 2s (in worst case 4s),
+    # In 32 node cluster, it took mostly about 2s or 4s (in worst case 14s)
+    # to get IPsec connections up with peer nodes.
+    # This is a best-effort attempt to bootstrap IPsec connections upfront to
+    # avoid disruptions, waiting longer would impact node reboot time.
     timeout=60
     elapsed=0
     desiredconn=""
@@ -41,7 +58,7 @@ contents:
        | awk 'NF {print $0"-in-1", $0"-out-1"}' \
        | tr '\n' ' '); then
         echo "failed to query OVS Geneve interfaces for desired IPsec connections"
-        exit 0
+        exit 1
       fi
       establishedsa=$(ipsec showstates | grep ESTABLISHED_CHILD_SA | grep -o '"[^"]*"' | sed 's/"//g' | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
       if [ "$desiredconn" == "$establishedsa" ]; then
@@ -56,4 +73,8 @@ contents:
 
     if [[ $elapsed -ge $timeout ]]; then
         echo "Timed out waiting, some connections are not established, desired conns $desiredconn, established conns $establishedsa"
+        # Not treating this as a hard failure since this is a best-effort wait,
+        # peer nodes may be down or still rebooting during fairly common parallel
+        # reboots.
+        exit 0
     fi
